### ISSUE TITLE
Free main struct.

### ISSUE THREAD

**Issue by YvanoffP** [Bima42/cub3d#3]
We should do the destroy func. to destroy and free the main structure (game).
Since we init all datas on 0 or NULL we can protect it pretty ez

**Comment by Bima42** [comment]
Function is created in main.c
Add to check when parsing will be over is this one works correctly.

**Comment by Bima42** [comment]
We should protect all malloc and dangerous functions by calling an exit_func who destroy everything then exit

**Comment by Bima42** [comment]
Stay to do : 

- [x] Protect all malloc
- [x] Check all error return

All done but had to check one more time

**Comment by Bima42** [comment]
closes with commit 2cba62c911c6300abbbf6eb5286b5389d76298bc
